local GameSession = require("tnr.core.game_session")
local EquipmentInstance = require("tnr.equipment.equipment_instance")
local Catalog = require("tnr.equipment.phase1_catalog")
local Manager = require("tnr.equipment.runtime.support_runtime_manager")

return function(assert_equal, assert_true)
    local session = GameSession.new({ run_seed = 1002 })
    session:start_new()
    local player = session:get_player(1)
    player.loadout:set_slot("supports", 1, EquipmentInstance.new(Catalog.definitions.test_support, 1))
    local manager = Manager.new(player.loadout, Catalog.registry)
    assert_equal(manager:entity_count(), 4, "support entity count comes from definition")
    local entities = manager:update(100, 50, "HIGH")
    assert_equal(#entities, 4, "support manager updates every entity")
    player.loadout:set_slot("supports", 1, EquipmentInstance.new(Catalog.definitions.test_support_alt, 1))
    player.loadout:set_slot("supports", 1, EquipmentInstance.new(Catalog.definitions.test_support, 1))
    local two = Manager.new(player.loadout, Catalog.registry)
    assert_true(two:entity_count() >= 4, "support count is independent of player power")
end
