-- Content-based difficulty tier per selectable wave (1 = lightest).
-- Equal-frequency buckets over the real wave pool, so each tier holds a
-- comparable amount of content. Generated from measured HP / enemy count /
-- duration / bullet density. Do not hand-edit.
return {
    ["legacy_karl_lunatic_wave_01"] = 1,
    ["legacy_sf_lunatic_wave_02"] = 1,
    ["legacy_sf_normal_wave_02"] = 1,
    ["legacy_sf_lunatic_wave_01"] = 1,
    ["legacy_sf_normal_wave_01"] = 1,
    ["legacy_smf_lunatic_wave_02"] = 1,
    ["legacy_karl_lunatic_wave_02"] = 1,
    ["legacy_karl_normal_wave_01"] = 1,
    ["legacy_ae_lunatic_wave_01"] = 2,
    ["legacy_ae_normal_wave_01"] = 2,
    ["legacy_qxs_lunatic_wave_01"] = 2,
    ["legacy_qxs_normal_wave_01"] = 2,
    ["legacy_smf_lunatic_wave_01"] = 2,
    ["legacy_wyj_lunatic_wave_01"] = 2,
    ["legacy_wyj_normal_wave_01"] = 2,
    ["legacy_xiv_lunatic_wave_01"] = 3,
    ["legacy_xiv_normal_wave_01"] = 3,
    ["legacy_void_lunatic_wave_01"] = 3,
    ["legacy_void_normal_wave_01"] = 3,
    ["legacy_void_lunatic_wave_02"] = 3,
    ["legacy_void_normal_wave_02"] = 3,
    ["legacy_xiv_lunatic_wave_02"] = 3,
    ["legacy_xiv_normal_wave_02"] = 4,
    ["legacy_xy_lunatic_wave_01"] = 4,
    ["legacy_xy_normal_wave_01"] = 4,
    ["legacy_lico_lunatic_wave_01"] = 4,
    ["legacy_xy_lunatic_wave_02"] = 4,
    ["legacy_lico_normal_wave_01"] = 4,
    ["legacy_xy_normal_wave_02"] = 4,
    ["legacy_kbz_lunatic_wave_01"] = 5,
    ["legacy_kbz_normal_wave_01"] = 5,
    ["legacy_smf_normal_wave_02"] = 5,
    ["legacy_stp_lunatic_wave_02"] = 5,
    ["legacy_smf_normal_wave_01"] = 5,
    ["legacy_stp_normal_wave_02"] = 5,
    ["legacy_stp_lunatic_wave_01"] = 5,
    ["legacy_stp_normal_wave_01"] = 6,
    ["legacy_yyzy_lunatic_wave_01"] = 6,
    ["legacy_yyzy_normal_wave_01"] = 6,
    ["legacy_er_lunatic_wave_01"] = 6,
    ["legacy_er_normal_wave_01"] = 6,
    ["legacy_olc_lunatic_wave_01"] = 6,
    ["legacy_olc_normal_wave_01"] = 6,
}
