-- Names registered by the reference editor export and shipped in
-- assets/audio/music.  The key is the original resource name, so loop points
-- remain those declared by MusicRecord instead of being replaced by a generic
-- loop.
return {
    { key = "menu", title = "主界面" },
    { key = "spellcard", title = "符卡练习" },
    { key = "はちみつれもん-二色莲花蝶", title = "二色莲花蝶" },
    { key = "龙と桜巫女", title = "龙と桜巫女" },
    { key = "スターインデペンデントデイズ", title = "スターインデペンデントデイズ" },
    { key = "BGM-YEWAN", title = "BGM-YEWAN" },
    { key = "BGM-TKZ-1", title = "BGM-TKZ-1" },
    { key = "BGM-TKZ-3", title = "BGM-TKZ-3" },
    { key = "BGM-MLS-1", title = "BGM-MLS-1" },
    { key = "BGM-MLS-2", title = "BGM-MLS-2" },
    { key = "BGM-LM-1", title = "BGM-LM-1" },
    { key = "BGM-LM-2", title = "BGM-LM-2" },
    { key = "BGM-YYC-2", title = "BGM-YYC-2" },
    { key = "XY-LSC", title = "XY-LSC" },
    { key = "qxs_GrayMoon", title = "qxs Gray Moon" },
    { key = "qxs_Mirror", title = "qxs Mirror" },
    { key = "Cirno_stage", title = "Cirno Stage" },
    { key = "Cirno", title = "Cirno Boss" },
    { key = "黄昏フロンティア - アンノウンＸ～Occultly Madness", title = "アンノウンＸ" },
    { key = "平安のエイリアン-上海アリス幻樂団", title = "平安のエイリアン" },
    { key = "stageBGM", title = "Stage BGM" },
    { key = "xiv_boss", title = "XIV Boss" },
    { key = "Still Love You", title = "Still Love You" },
    { key = "Heavy Long", title = "Heavy Long" },
    { key = "DFKtaisabachi_W", title = "DFKtaisabachi" },
    { key = "妖怪宇宙旅行", title = "妖怪宇宙旅行" },
    { key = "绵月的符卡", title = "绵月的符卡" },
    { key = "AE_bgm_road", title = "AE Road" },
    { key = "AE_bgm-final", title = "AE Final" },
    { key = "静寂の祭 ~ the shadow in the library", title = "静寂の祭" },
    { key = "贤者の密室 ~ roaring element", title = "贤者の密室" },
    { key = "wyj_Roadbgm", title = "WYJ Road" },
    { key = "wyj_Alicebgm2", title = "WYJ Alice" },
    { key = "wyj_Shinkibgm", title = "WYJ Shinki" },
    { key = "th12.8_07", title = "th12.8 Stage" },
    { key = "Solar", title = "Solar" },
    { key = "star", title = "Star" },
    { key = "dBu music - 雾雨 ~ Loose Rain", title = "Loose Rain" },
    { key = "BGM BOSS", title = "BGM BOSS" },
    { key = "Mid Boss1", title = "Mid Boss 1" },
    { key = "Mid Boss2", title = "Mid Boss 2" },
    { key = "格兰之森", title = "格兰之森" },
    { key = "赛丽亚（旧）", title = "赛丽亚（旧）" },
    { key = "格拉卡、烈焰格拉卡", title = "格拉卡、烈焰格拉卡" },
    { key = "OLC_マジカルストーム", title = "マジカルストーム" },
    { key = "black opal labyrinth", title = "black opal labyrinth" },
    { key = "tenka_bgm", title = "Tenka BGM" },
    { key = "tenka_lsc", title = "Tenka Last Spell" },
    { key = "yahoon-road", title = "Yahoon Road" },
    { key = "yahoon-boss", title = "Yahoon Boss" },
}
