local Command = {
    SELECT_NODE = "SELECT_NODE",
    START_ENCOUNTER = "START_ENCOUNTER",
    ADD_MONEY = "ADD_MONEY",
    ADD_SCORE = "ADD_SCORE",
    ADD_LIFE = "ADD_LIFE",
    ADD_BOMB = "ADD_BOMB",
    RETURN_TO_MAP = "RETURN_TO_MAP",
    COMPLETE_BATTLE = "COMPLETE_BATTLE",
    DEBUG_GOD = "DEBUG_GOD",
    DEBUG_KILL_ALL = "DEBUG_KILL_ALL",
    DEBUG_CLEAR = "DEBUG_CLEAR",
    DEBUG_CLEAR_REWARD = "DEBUG_CLEAR_REWARD",
    DEBUG_GOTO = "DEBUG_GOTO",
    DEBUG_MAP_REVEAL = "DEBUG_MAP_REVEAL",
}

return Command
