local Event = {
    NODE_SELECTED = "NODE_SELECTED",
    MAP_ENTERED = "MAP_ENTERED",
    ENCOUNTER_STARTED = "ENCOUNTER_STARTED",
    PLACEHOLDER_ENTERED = "PLACEHOLDER_ENTERED",
    BATTLE_CLEARED = "BATTLE_CLEARED",
    BATTLE_FAILED = "BATTLE_FAILED",
    REWARD_GRANTED = "REWARD_GRANTED",
    RUN_CLEARED = "RUN_CLEARED",
    PLAYER_ADDED = "PLAYER_ADDED",
    PLAYER_REMOVED = "PLAYER_REMOVED",
    MONEY_ADDED = "MONEY_ADDED",
    SCORE_ADDED = "SCORE_ADDED",
    LIFE_CHANGED = "LIFE_CHANGED",
    BOMB_CHANGED = "BOMB_CHANGED",
    DEBUG_CHANGED = "DEBUG_CHANGED",
}

return Event
