#!/usr/bin/env python3
"""Extract per-enemy-class combat metrics from the reference activity7 export.

The reference project stores no numeric difficulty: each enemy class only
declares which mode it belongs to ("Normal"/"Lunatic"/"All"). To build a
content-based difficulty we read two real signals from the reference export:

  * enemy.init(self, style, hp, ...)  -> the class HP
  * _create_bullet_group / _create_bullet occurrences -> bullet density

The result is written to game/scripts/tnr/stages/reference_enemy_stats.lua and
is consumed by tnr.stages.wave_difficulty.

Usage:
    python tools/extract_reference_enemy_stats.py [path/to/_editor_output.lua]
"""
import re
import os
import sys

DEFAULT_SOURCE = r"E:\gemesmods\stg\_reference_extract_20260827\activity7\_editor_output.lua"
DEFAULT_OUTPUT = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "game", "scripts", "tnr", "stages", "reference_enemy_stats.lua",
)
WAVE_CATALOG = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "game", "scripts", "tnr", "stages", "legacy_enemy_waves.lua",
)


def lua_string(value):
    return value.replace("\\", "\\\\").replace('"', '\\"')


def lua_number(value):
    if value is None:
        return "nil"
    number = float(value)
    if number.is_integer():
        return str(int(number))
    return ("%.4f" % number).rstrip("0").rstrip(".")


def parse_blocks(source):
    class_re = re.compile(r'_editor_class\["([^"]+)"\]=Class\((\w+)\)')
    blocks = {}
    current = None
    buffer = []
    for line in source.split("\n"):
        match = class_re.search(line)
        if match:
            if current is not None:
                blocks[current] = buffer
            current = match.group(1)
            buffer = []
        elif current is not None:
            buffer.append(line)
            if len(buffer) > 400:
                blocks[current] = buffer
                current = None
    if current is not None:
        blocks[current] = buffer
    return blocks


def main():
    source_path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_SOURCE
    if not os.path.isfile(source_path):
        raise SystemExit("reference source not found: %s" % source_path)
    with open(source_path, encoding="utf-8", errors="replace") as handle:
        source = handle.read()

    blocks = parse_blocks(source)
    stats = {}
    for name, buffer in blocks.items():
        text = "\n".join(buffer)
        match = re.search(r"enemy\.init\(self,\s*([0-9.]+),\s*([0-9.]+)", text)
        style = float(match.group(1)) if match else None
        hp = float(match.group(2)) if match else None
        bullets = len(re.findall(r"_create_bullet_group|_create_bullet|CreateShot", text))
        stats[name] = {"hp": hp, "bullets": bullets, "style": style}

    # Only keep classes referenced by the generated wave catalog.
    referenced = set()
    if os.path.isfile(WAVE_CATALOG):
        with open(WAVE_CATALOG, encoding="utf-8", errors="replace") as handle:
            referenced = set(re.findall(r'"([^"]+:(?:Normal|Lunatic))"', handle.read()))

    names = sorted(c for c in stats if not referenced or c in referenced)
    lines = [
        "-- Per-enemy-class combat metrics extracted from the reference activity7",
        "-- export (_editor_output.lua). HP comes from the real enemy.init(style, hp)",
        "-- call; bullets counts the _create_bullet_group/_create_bullet sites in that",
        "-- class. Used to derive a content-based difficulty score per wave.",
        "-- Generated by tools/extract_reference_enemy_stats.py. Do not hand-edit.",
        "return {",
    ]
    for name in names:
        entry = stats[name]
        lines.append(
            '    ["%s"] = { hp = %s, bullets = %s, style = %s },'
            % (lua_string(name), lua_number(entry["hp"]), lua_number(entry["bullets"]), lua_number(entry["style"]))
        )
    lines.append("}")
    with open(DEFAULT_OUTPUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines) + "\n")
    print("wrote %s (%d entries)" % (DEFAULT_OUTPUT, len(names)))


if __name__ == "__main__":
    main()
