-- Regenerate the three-floor boss and elite pools.
--
-- Full bosses (>=3 cards) and short "elite" bosses (1-2 cards) are scored by
-- measured card count and card HP, sorted and split into three equal-frequency
-- floors, then written to tnr/stages/boss_floor_pools.lua.
--
-- Run from the game directory with the bundled Lua:
--   ..\LuaSTG-Sub-master\tool\lua\lua54.exe tools/generate_boss_pools.lua

package.path = "game/scripts/?.lua;game/scripts/?/init.lua;" .. package.path

local ContentCatalog = require("tnr.stages.content_catalog")

local function log10_plus_one(value)
    local number = tonumber(value) or 0
    if number < 0 then number = 0 end
    return math.log(number + 1) / math.log(10)
end

-- Aggregate the real card metrics per legacy boss class.
local by_boss = {}
for _, card in pairs(ContentCatalog.cards) do
    if card.legacy_boss and card.legacy_exact then
        local boss = by_boss[card.legacy_boss] or { spells = 0, nonspells = 0, hp = 0 }
        if card.is_spell then boss.spells = boss.spells + 1 else boss.nonspells = boss.nonspells + 1 end
        boss.hp = math.max(boss.hp, tonumber(card.hp) or 0)
        by_boss[card.legacy_boss] = boss
    end
end

local rows = {}
for boss, data in pairs(by_boss) do
    -- The dialogue placeholder HP is not a real combat value.
    local hp = data.hp
    if hp >= 100000 then hp = 3000 end
    local total = data.spells + data.nonspells
    local score = 0.9 * log10_plus_one(hp)
        + 0.85 * log10_plus_one(data.spells)
        + 0.5 * log10_plus_one(data.nonspells)
        + 0.5 * log10_plus_one(total)
    rows[#rows + 1] = { boss = boss, total = total, score = score }
end

local function split_three(list)
    table.sort(list, function(left, right)
        if left.score ~= right.score then return left.score < right.score end
        return left.boss < right.boss
    end)
    local buckets = { {}, {}, {} }
    local count = #list
    for index, row in ipairs(list) do
        local floor = math.min(3, math.floor((index - 1) * 3 / count) + 1)
        buckets[floor][#buckets[floor] + 1] = row.boss
    end
    for floor = 1, 3 do table.sort(buckets[floor]) end
    return buckets
end

local bosses, elites = {}, {}
for _, row in ipairs(rows) do
    if row.total >= 3 then bosses[#bosses + 1] = row
    elseif row.total >= 1 then elites[#elites + 1] = row end
end
bosses = split_three(bosses)
elites = split_three(elites)

local lines = {
    "-- Auto-tiered boss and elite pools (3 floors).",
    "-- Tiered by measured card count and card HP from the reference export.",
    "-- Floor 1 = lightest, floor 3 = heaviest. Generated by tools/generate_boss_pools.lua.",
    "-- Do not hand-edit.",
    "return {",
    "    bosses = {",
}
for floor = 1, 3 do
    lines[#lines + 1] = "        [" .. floor .. "] = {"
    for _, boss in ipairs(bosses[floor]) do
        lines[#lines + 1] = string.format('            ["%s"] = true,', boss)
    end
    lines[#lines + 1] = "        },"
end
lines[#lines + 1] = "    },"
lines[#lines + 1] = "    elites = {"
for floor = 1, 3 do
    lines[#lines + 1] = "        [" .. floor .. "] = {"
    for _, boss in ipairs(elites[floor]) do
        lines[#lines + 1] = string.format('            ["%s"] = true,', boss)
    end
    lines[#lines + 1] = "        },"
end
lines[#lines + 1] = "    },"
lines[#lines + 1] = "}"

local path = "game/scripts/tnr/stages/boss_floor_pools.lua"
local file = assert(io.open(path, "w"))
file:write(table.concat(lines, "\n") .. "\n")
file:close()

for floor = 1, 3 do
    print(string.format("floor %d: %d bosses, %d elites", floor, #bosses[floor], #elites[floor]))
end
print("wrote " .. path)
