param(
    [string]$ActivityRoot = "E:\gemesmods\stg\TouHouNightReign\game\legacy\assets\activity7",
    [string]$DataRoot = "E:\gemesmods\stg\TouHouNightReign\game\legacy\assets\data",
    [string]$JsonOutput = "E:\gemesmods\stg\TouHouNightReign\game\assets\reference\legacy_resources.json",
    [string]$LuaOutput = "E:\gemesmods\stg\TouHouNightReign\game\scripts\tnr\stages\legacy_resources.lua"
)

function Get-Category([string]$relative, [string]$extension) {
    $name = [IO.Path]::GetFileName($relative).ToLowerInvariant()
    $ext = $extension.ToLowerInvariant()
    if ($ext -in @('.ogg', '.mp3', '.flac')) { return 'music' }
    if ($ext -in @('.wav', '.mid')) { return 'sound' }
    if ($ext -in @('.ttf', '.otf', '.fnt')) { return 'font' }
    if ($ext -in @('.fx', '.psi')) { return 'effect' }
    if ($name -match '(^|[_-])(bg|background|scbg|stgbg|ground|mask|shade|shadow|mirror|glow)') { return 'background' }
    if ($name -match '(boss|face|dialog|talk|reimu|marisa|sanae|cirno|junko|larva|mystia|wuer)') { return 'character' }
    if ($name -match '(bullet|laser|arrow|ball|grain|ring|orb|star|fire|shot)') { return 'bullet' }
    if ($name -match '(effect|ef|charge|caution|distort|smear|particle)') { return 'effect' }
    if ($ext -in @('.png', '.jpg', '.jpeg', '.bmp', '.webp')) { return 'texture' }
    if ($ext -eq '.lua') { return 'script' }
    return 'other'
}

function To-ProjectPath([string]$rootName, [string]$relative) {
    return ("legacy/{0}/{1}" -f $rootName, ($relative -replace '\\', '/'))
}

$entries = @()
foreach ($source in @(
    [pscustomobject]@{ Root = $ActivityRoot; Name = 'activity7' },
    [pscustomobject]@{ Root = $DataRoot; Name = 'data' }
)) {
    if (-not (Test-Path -LiteralPath $source.Root)) { continue }
    foreach ($file in Get-ChildItem -LiteralPath $source.Root -Recurse -File) {
        $relative = $file.FullName.Substring($source.Root.Length).TrimStart('\', '/')
        $hash = (Get-FileHash -Algorithm SHA256 -LiteralPath $file.FullName).Hash.ToLowerInvariant()
        $entries += [pscustomobject]@{
            id = ("legacy_{0}_{1}" -f $source.Name, (($relative -replace '\\', '/' -replace '[^A-Za-z0-9]+', '_').Trim('_').ToLowerInvariant()))
            category = Get-Category $relative $file.Extension
            source_root = $source.Name
            source_path = $relative -replace '\\', '/'
            project_path = To-ProjectPath $source.Name $relative
            extension = $file.Extension.ToLowerInvariant()
            bytes = [int64]$file.Length
            sha256 = $hash
        }
    }
}
$entries = @($entries | Sort-Object category, source_root, source_path)
$manifest = [pscustomobject]@{
    schema = 1
    generated_from = @('activity7/_editor_output.lua', 'data/THlib.lua')
    source_roots = @{
        activity7 = 'game/legacy/assets/activity7/'
        data = 'game/legacy/assets/data/'
    }
    categories = @('background', 'character', 'bullet', 'effect', 'sound', 'music', 'font', 'texture', 'script', 'other')
    resources = $entries
}
$jsonParent = Split-Path -Parent $JsonOutput
$luaParent = Split-Path -Parent $LuaOutput
New-Item -ItemType Directory -Force -Path $jsonParent, $luaParent | Out-Null
$manifest | ConvertTo-Json -Depth 6 | Set-Content -LiteralPath $JsonOutput -Encoding UTF8

function LuaQuote([string]$value) {
    return '"' + ($value.Replace('\', '\\').Replace('"', '\"')) + '"'
}
$lua = [Text.StringBuilder]::new()
[void]$lua.AppendLine('-- Generated by tools/generate_legacy_resource_manifest.ps1.')
[void]$lua.AppendLine('-- Paths are project-relative and point to the preserved original assets.')
[void]$lua.AppendLine('return {')
foreach ($entry in $entries) {
    [void]$lua.AppendLine(('    {{ id = {0}, category = {1}, source_root = {2}, source_path = {3}, project_path = {4}, extension = {5}, bytes = {6}, sha256 = {7} }},' -f `
        (LuaQuote $entry.id), (LuaQuote $entry.category), (LuaQuote $entry.source_root), (LuaQuote $entry.source_path), (LuaQuote $entry.project_path), (LuaQuote $entry.extension), $entry.bytes, (LuaQuote $entry.sha256)))
}
[void]$lua.AppendLine('}')
[IO.File]::WriteAllText($LuaOutput, $lua.ToString(), [Text.UTF8Encoding]::new($false))
Write-Output "Generated $($entries.Count) resources."
